# .github/workflows/airdrop-bot.yml
name: Run CuanWatcher Bot

on:
  schedule:
    - cron: '0 * * * *'  # Jalankan tiap jam (pada menit ke-0)
  workflow_dispatch:     # Bisa juga dijalankan manual

jobs:
  send-airdrop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-telegram-bot

      - name: Run bot
        run: python bot.py
        env:
          TELEGRAM_TOKEN: ${{ secrets. 8470753110:AAGEVdpJAU3RUoBjcIu3Wwve-2oKgyVVHoE }}
          TELEGRAM_CHAT_ID: ${{ secrets. 6608544965 }}
